//AUTH
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

//VIDEOS
export const VIDEOS_FETCH_ALL = 'VIDEOS_FETCH_ALL';

//VIDEO
export const VIDEO_FETCH = 'VIDEO_FETCH';
export const VIDEO_CLEAN = 'VIDEO_CLEAN';
export const SAVE_RATING = 'SAVE_RATING';
